version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ijoke
      POSTGRES_PASSWORD: ijoke
      POSTGRES_DB: ijoke
    ports:
      - 5430:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local